[project]
name = "coding-assistant"
version = "0.1.0"
description = "Coding Assistant is an advanced Python-based project designed to streamline and automate various coding tasks."
readme = "README.md"
authors = []
requires-python = ">=3.12"
dependencies = [
    "smolagents[openai]>=1.13.0",
]

[project.scripts]
coding-assistant = "coding_assistant:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
