[project]
name = "coding-assistant"
version = "0.1.0"
description = "Coding Assistant is an advanced Python-based project designed to streamline and automate various coding tasks."
readme = "README.md"
authors = []
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.66.3",
    "mcp[cli]>=1.6.0",
    "opentelemetry-api>=1.32.1",
    "opentelemetry-exporter-otlp-proto-http>=1.32.1",
    "opentelemetry-sdk>=1.32.1",
    "rich>=14.0.0",
    "requests>=2.31.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-xdist>=3.6.1",
]

[tool.black]
line-length = 120

[project.scripts]
coding-assistant = "coding_assistant.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
